"""refactor Firmwares

Revision ID: 12de90987a4f
Revises: 64daed0428bc
Create Date: 2023-12-20 01:04:15.106996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12de90987a4f'
down_revision: Union[str, None] = '64daed0428bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('firmwares', 'truck_model',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('firmwares', 'engine_model',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('firmwares', 'ecu_model',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('firmwares', 'flasher',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('firmwares', 'flasher',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('firmwares', 'ecu_model',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('firmwares', 'engine_model',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('firmwares', 'truck_model',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
