"""Foreign_keys_add

Revision ID: 320974e76ea3
Revises: 02ca901a3dc5
Create Date: 2023-12-07 23:52:23.258854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '320974e76ea3'
down_revision: Union[str, None] = '02ca901a3dc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'firmwares', 'users', ['user_uploaded'], ['name'])
    op.create_foreign_key(None, 'modified_firmwares', 'users', ['user_uploaded'], ['name'])
    op.create_foreign_key(None, 'modified_firmwares', 'firmware_calibrators', ['calibrator_name'], ['name'])
    op.create_foreign_key(None, 'modified_firmwares', 'firmwares', ['file_name_original'], ['file_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'modified_firmwares', type_='foreignkey')
    op.drop_constraint(None, 'modified_firmwares', type_='foreignkey')
    op.drop_constraint(None, 'modified_firmwares', type_='foreignkey')
    op.drop_constraint(None, 'firmwares', type_='foreignkey')
    # ### end Alembic commands ###
