"""refactor Firmwares

Revision ID: 64daed0428bc
Revises: b654b993a489
Create Date: 2023-12-20 01:00:45.388054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64daed0428bc'
down_revision: Union[str, None] = 'b654b993a489'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('firmwares', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('firmwares', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
